### ISSUE TITLE
Cant run BouncyBall

### ISSUE THREAD

**Issue by AndreyNazarchuk** [jython234/BouncyBall#1]
I installed Maven, set the PATH and JAVA_HOME variables properly, and did mvn package.
I succeeded, and then I tried to do the java -jar BouncyBall-1.0-SNAPSHOT.jar and it said:
C:\Windows\system32>java -jar BouncyBall-1.0-SNAPSHOT.jar
Error: Unable to access jarfile BouncyBall-1.0-SNAPSHOT.jar

**Comment by alejzeis** [comment]
It seems you are in the wrong directory.

On Wednesday, April 8, 2015, Andrey Nazarchuk notifications@github.com
wrote:

> I installed Maven, set the PATH and JAVA_HOME variables properly, and did
> mvn package.
> I succeeded, and then I tried to do the java -jar
> BouncyBall-1.0-SNAPSHOT.jar and it said:
> C:\Windows\system32>java -jar BouncyBall-1.0-SNAPSHOT.jar
> Error: Unable to access jarfile BouncyBall-1.0-SNAPSHOT.jar
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jython234/BouncyBall/issues/1.

##

**Comment by AndreyNazarchuk** [comment]
Can't be, I went to the "target" folder in the BouncyBall zip and did "open
command window here"

**Comment by alejzeis** [comment]
You need to extract the zip first :).

On Wednesday, April 8, 2015, Andrey Nazarchuk notifications@github.com
wrote:

> Can't be, I went to the "target" folder in the BouncyBall zip and did "open
> command window here"
> On Apr 8, 2015 4:37 PM, "jython234" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > It seems you are in the wrong directory.
> > 
> > On Wednesday, April 8, 2015, Andrey Nazarchuk <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> > 
> > > I installed Maven, set the PATH and JAVA_HOME variables properly, and
> > > did
> > > mvn package.
> > > I succeeded, and then I tried to do the java -jar
> > > BouncyBall-1.0-SNAPSHOT.jar and it said:
> > > C:\Windows\system32>java -jar BouncyBall-1.0-SNAPSHOT.jar
> > > Error: Unable to access jarfile BouncyBall-1.0-SNAPSHOT.jar
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/jython234/BouncyBall/issues/1.
> > 
> > ## 
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jython234/BouncyBall/issues/1#issuecomment-91068831
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jython234/BouncyBall/issues/1#issuecomment-91069069.

##

**Comment by AndreyNazarchuk** [comment]
I did lol, :file_folder: Give me some credit

**Comment by alejzeis** [comment]
try again, but in a new fresh folder. You must build in the extracted
folder (and run).

On Wednesday, April 8, 2015, Andrey Nazarchuk notifications@github.com
wrote:

> I did lol
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jython234/BouncyBall/issues/1#issuecomment-91088879.

##

**Comment by AndreyNazarchuk** [comment]
Exactly what I did

**Comment by alejzeis** [comment]
I will build the latest version and upload it for you if its not working.

On Wednesday, April 8, 2015, Andrey Nazarchuk notifications@github.com
wrote:

> Exactly what I did
> On Apr 8, 2015 6:59 PM, "jython234" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > try again, but in a new fresh folder. You must build in the extracted
> > folder (and run).
> > 
> > On Wednesday, April 8, 2015, Andrey Nazarchuk <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> > 
> > > I did lol
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/jython234/BouncyBall/issues/1#issuecomment-91088879
> > > .
> > 
> > ## 
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jython234/BouncyBall/issues/1#issuecomment-91089567
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jython234/BouncyBall/issues/1#issuecomment-91094985.

##

**Comment by AndreyNazarchuk** [comment]
Ok, yes please. :)

**Comment by alejzeis** [comment]
@AndreyNazarchuk https://drive.google.com/file/d/0B-XjWjitgIiyOVhkdkY1QWRtdmM/view?usp=sharing

**Comment by AndreyNazarchuk** [comment]
Thank you!
